import type {
  Guest,
  CheckIn,
  Registration,
  Hospitality,
  Venue,
  Event,
  Staff,
  Notification,
  DashboardStats,
  ActivityFeedItem,
  Customer,
  SpaAppointment,
  CalendarStaff,
  SpaService,
} from '@/types';

// ============ Dashboard Stats ============
export const mockDashboardStats: DashboardStats = {
  todayCheckIns: 248,
  guestsArrived: 1247,
  pendingGuests: 153,
  hospitalityBookings: 89,
  venueOccupancy: 78,
  totalGuests: 1400,
  totalEvents: 12,
  activeStaff: 45,
};

// ============ Guests ============
export const mockGuests: Guest[] = [
  {
    id: '1',
    name: 'Sarah Anderson',
    email: 'sarah.anderson@company.com',
    phone: '+1 (555) 123-4567',
    company: 'Tech Corp',
    designation: 'CEO',
    category: 'VIP',
    status: 'active',
    checkedIn: true,
    checkInTime: '2024-01-15T09:30:00Z',
    registrationDate: '2024-01-10T10:00:00Z',
    qrCode: 'QR001',
    tags: ['VIP', 'Speaker'],
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@startup.io',
    phone: '+1 (555) 234-5678',
    company: 'Startup IO',
    designation: 'CTO',
    category: 'Speaker',
    status: 'active',
    checkedIn: false,
    registrationDate: '2024-01-12T14:30:00Z',
    qrCode: 'QR002',
    tags: ['Speaker', 'Tech'],
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.r@designstudio.com',
    phone: '+1 (555) 345-6789',
    company: 'Design Studio',
    designation: 'Creative Director',
    category: 'Delegate',
    status: 'active',
    checkedIn: true,
    checkInTime: '2024-01-15T08:45:00Z',
    registrationDate: '2024-01-11T16:20:00Z',
    qrCode: 'QR003',
    tags: ['Delegate'],
  },
];

// ============ Check-ins ============
export const mockCheckIns: CheckIn[] = [
  {
    id: '1',
    guestId: '1',
    guestName: 'Sarah Anderson',
    guestEmail: 'sarah.anderson@company.com',
    checkInTime: '2024-01-15T09:30:00Z',
    checkInMethod: 'QR',
    venue: 'Main Hall',
    event: 'Tech Summit 2024',
    badgePrinted: true,
    verifiedBy: 'John Staff',
  },
  {
    id: '2',
    guestId: '3',
    guestName: 'Emily Rodriguez',
    guestEmail: 'emily.r@designstudio.com',
    checkInTime: '2024-01-15T08:45:00Z',
    checkInMethod: 'Manual',
    venue: 'Main Hall',
    event: 'Tech Summit 2024',
    badgePrinted: true,
    verifiedBy: 'Jane Staff',
  },
];

// ============ Registrations ============
export const mockRegistrations: Registration[] = [
  {
    id: '1',
    guestName: 'Sarah Anderson',
    guestEmail: 'sarah.anderson@company.com',
    phone: '+1 (555) 123-4567',
    event: 'Tech Summit 2024',
    registrationDate: '2024-01-10T10:00:00Z',
    status: 'confirmed',
    paymentStatus: 'paid',
    amount: 500,
    category: 'VIP',
  },
  {
    id: '2',
    guestName: 'Michael Chen',
    guestEmail: 'michael.chen@startup.io',
    phone: '+1 (555) 234-5678',
    event: 'Tech Summit 2024',
    registrationDate: '2024-01-12T14:30:00Z',
    status: 'pending',
    paymentStatus: 'pending',
    amount: 350,
    category: 'Speaker',
  },
];

// ============ Hospitality ============
export const mockHospitality: Hospitality[] = [
  {
    id: '1',
    guestId: '1',
    guestName: 'Sarah Anderson',
    type: 'Hotel',
    description: 'Grand Hotel - Presidential Suite',
    status: 'confirmed',
    bookingDate: '2024-01-10T10:00:00Z',
    serviceDate: '2024-01-15T00:00:00Z',
    venue: 'Grand Hotel',
    cost: 500,
  },
  {
    id: '2',
    guestId: '1',
    guestName: 'Sarah Anderson',
    type: 'Airport Pickup',
    description: 'Airport transfer - Luxury sedan',
    status: 'completed',
    bookingDate: '2024-01-10T10:00:00Z',
    serviceDate: '2024-01-14T18:00:00Z',
    cost: 80,
  },
  {
    id: '3',
    guestId: '2',
    guestName: 'Michael Chen',
    type: 'Meal',
    description: 'VIP Dinner - Day 1',
    status: 'pending',
    bookingDate: '2024-01-12T14:30:00Z',
    serviceDate: '2024-01-15T19:00:00Z',
    venue: 'Main Hall',
    cost: 150,
  },
];

// ============ Venues ============
export const mockVenues: Venue[] = [
  {
    id: '1',
    name: 'Main Hall',
    capacity: 500,
    currentOccupancy: 380,
    type: 'Conference Hall',
    location: 'Building A - Ground Floor',
    status: 'active',
    amenities: ['WiFi', 'Projector', 'Sound System', 'AC', 'Stage'],
  },
  {
    id: '2',
    name: 'Meeting Room 1',
    capacity: 50,
    currentOccupancy: 35,
    type: 'Meeting Room',
    location: 'Building B - 2nd Floor',
    status: 'active',
    amenities: ['WiFi', 'TV Screen', 'Whiteboard', 'AC'],
  },
  {
    id: '3',
    name: 'Auditorium',
    capacity: 1000,
    currentOccupancy: 0,
    type: 'Auditorium',
    location: 'Building A - 3rd Floor',
    status: 'inactive',
    amenities: ['WiFi', 'Stage', 'Sound System', 'Lighting', 'AC', 'Recording'],
  },
];

// ============ Events ============
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Tech Summit 2024',
    description: 'Annual technology conference',
    startDate: '2024-01-15T09:00:00Z',
    endDate: '2024-01-17T18:00:00Z',
    venue: 'Main Hall',
    venueId: '1',
    status: 'active',
    attendees: 380,
    capacity: 500,
    category: 'Conference',
    organizer: 'Tech Corp',
  },
  {
    id: '2',
    title: 'Workshop: AI & ML',
    description: 'Hands-on workshop on AI and Machine Learning',
    startDate: '2024-01-16T14:00:00Z',
    endDate: '2024-01-16T17:00:00Z',
    venue: 'Meeting Room 1',
    venueId: '2',
    status: 'active',
    attendees: 35,
    capacity: 50,
    category: 'Workshop',
    organizer: 'AI Labs',
  },
];

// ============ Staff ============
export const mockStaff: Staff[] = [
  {
    id: '1',
    name: 'John Staff',
    email: 'john.staff@entryflow.com',
    phone: '+1 (555) 111-2222',
    role: 'manager',
    department: 'Operations',
    status: 'active',
    joinedDate: '2023-06-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Jane Staff',
    email: 'jane.staff@entryflow.com',
    phone: '+1 (555) 222-3333',
    role: 'staff',
    department: 'Registration',
    status: 'active',
    joinedDate: '2023-08-20T00:00:00Z',
  },
];

// ============ Notifications ============
export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'New Guest Registration',
    message: 'Sarah Anderson registered for Tech Summit 2024',
    type: 'info',
    read: false,
    createdAt: '2024-01-15T09:30:00Z',
  },
  {
    id: '2',
    title: 'Check-in Complete',
    message: 'Emily Rodriguez checked in successfully',
    type: 'success',
    read: false,
    createdAt: '2024-01-15T09:25:00Z',
  },
  {
    id: '3',
    title: 'Venue at Capacity',
    message: 'Main Hall is at 90% capacity',
    type: 'warning',
    read: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
];

// ============ Activity Feed ============
export const mockActivityFeed: ActivityFeedItem[] = [
  {
    id: '1',
    type: 'check_in',
    title: 'Guest Checked In',
    description: 'Sarah Anderson checked in at Main Hall',
    timestamp: '2024-01-15T09:30:00Z',
    user: 'John Staff',
  },
  {
    id: '2',
    type: 'registration',
    title: 'New Registration',
    description: 'Michael Chen registered for Tech Summit 2024',
    timestamp: '2024-01-15T09:20:00Z',
  },
  {
    id: '3',
    type: 'hospitality',
    title: 'Hospitality Booking',
    description: 'Hotel booking confirmed for Sarah Anderson',
    timestamp: '2024-01-15T09:10:00Z',
    user: 'Jane Staff',
  },
  {
    id: '4',
    type: 'event',
    title: 'Event Started',
    description: 'Tech Summit 2024 has started',
    timestamp: '2024-01-15T09:00:00Z',
  },
];

// ============ Chart Data ============
export const mockCheckInTrends = [
  { name: 'Mon', value: 45 },
  { name: 'Tue', value: 67 },
  { name: 'Wed', value: 89 },
  { name: 'Thu', value: 124 },
  { name: 'Fri', value: 156 },
  { name: 'Sat', value: 187 },
  { name: 'Sun', value: 92 },
];

export const mockGuestCategories = [
  { name: 'VIP', value: 150, label: '15%' },
  { name: 'Speaker', value: 80, label: '8%' },
  { name: 'Delegate', value: 600, label: '60%' },
  { name: 'Staff', value: 120, label: '12%' },
  { name: 'Press', value: 50, label: '5%' },
];

export const mockVenueUtilization = [
  { name: 'Main Hall', value: 76 },
  { name: 'Meeting Room 1', value: 70 },
  { name: 'Meeting Room 2', value: 45 },
  { name: 'Auditorium', value: 0 },
  { name: 'Banquet Hall', value: 85 },
];

export const mockMonthlyStats = [
  { name: 'Jan', guests: 1200, events: 8, revenue: 45000 },
  { name: 'Feb', guests: 980, events: 6, revenue: 38000 },
  { name: 'Mar', guests: 1450, events: 10, revenue: 52000 },
  { name: 'Apr', guests: 1680, events: 12, revenue: 61000 },
  { name: 'May', guests: 1320, events: 9, revenue: 48000 },
  { name: 'Jun', guests: 1550, events: 11, revenue: 56000 },
];

// ============ Spa Services ============
export const mockSpaServices: SpaService[] = [
  { id: 's1', name: 'Consultation', duration: 30, room: 'Suite A' },
  { id: 's2', name: 'Standard session', duration: 60, room: 'Room 1' },
  { id: 's3', name: 'Extended session', duration: 90, room: 'Room 2' },
  { id: 's4', name: 'Group session', duration: 60, room: 'Room 4' },
];

// ============ Calendar Staff ============
export const mockCalendarStaff: CalendarStaff[] = [
  { id: 'st1', shortName: 'A. Okonjo', rooms: 'Rooms 1–2' },
  { id: 'st2', shortName: 'M. Reyes', rooms: 'Room 3' },
  { id: 'st3', shortName: 'T. Lindqvist', rooms: 'Room 4' },
  { id: 'st4', shortName: 'J. Park', rooms: 'Suite A' },
];

// ============ Customers (Spa members) ============
export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    name: 'Adaeze Nwosu',
    initials: 'AN',
    email: 'a.nwosu@fieldnote.co',
    phone: '(415) 555-0132',
    preferredContact: 'SMS',
    preferences: 'Mornings, quiet room',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Founding',
    memberSince: 'Mar 2019',
    visits: 64,
    upcomingCount: 2,
    missedVisits: 0,
    notes: 'Prefers the quiet room at the back. Citrus allergy — no citrus-based products. Books herself; do not call, text only.',
    hasAllergy: true,
    allergyNote: 'Citrus allergy',
    customerId: 'C1-L1',
    lastVisit: '28 Jul 2026',
    nextAppointment: 'Today 12:00 pm',
    photoUrl: undefined,
  },
  {
    id: 'c2',
    name: 'Cleo Fairbanks',
    initials: 'CF',
    email: 'cleodfairbanks@gmail.com',
    phone: '(415) 555-0187',
    preferredContact: 'Email',
    preferences: 'Afternoons',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Signature',
    memberSince: 'Jun 2020',
    visits: 31,
    upcomingCount: 1,
    missedVisits: 1,
    notes: 'Prefers afternoon appointments. No specific product restrictions.',
    customerId: 'C2-L1',
    lastVisit: '21 Jul 2026',
    nextAppointment: 'Today 9:00 am',
    photoUrl: undefined,
  },
  {
    id: 'c3',
    name: 'Tarquin Osei',
    initials: 'TO',
    email: 'tarquinosei@pm.me',
    phone: '(415) 555-0209',
    preferredContact: 'Call',
    preferences: 'No preference',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Standard',
    memberSince: 'Feb 2022',
    visits: 12,
    upcomingCount: 0,
    missedVisits: 2,
    notes: 'Has missed two appointments this year. Confirm by phone 24h ahead.',
    customerId: 'C3-L1',
    lastVisit: '10 Jul 2026',
    nextAppointment: undefined,
    photoUrl: undefined,
  },
  {
    id: 'c4',
    name: 'Marisol Venegas',
    initials: 'MV',
    email: 'm.venegas@studio44.com',
    phone: '(415) 555-0341',
    preferredContact: 'SMS',
    preferences: 'Evenings, aromatherapy',
    homeLocation: 'Harbor Street',
    balance: 40,
    tier: 'Founding',
    memberSince: 'Jan 2019',
    visits: 72,
    upcomingCount: 1,
    missedVisits: 0,
    notes: 'Loves aromatherapy add-ons. Prefers M. Reyes for extended sessions.',
    hasAllergy: false,
    customerId: 'C4-L1',
    lastVisit: '01 Aug 2026',
    nextAppointment: 'Today 2:00 pm',
    photoUrl: undefined,
  },
  {
    id: 'c5',
    name: 'Phineas Burke',
    initials: 'PB',
    email: 'p.burke@burkeandco.io',
    phone: '(415) 555-0478',
    preferredContact: 'Email',
    preferences: 'Early mornings',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Signature',
    memberSince: 'Aug 2021',
    visits: 24,
    upcomingCount: 1,
    missedVisits: 0,
    notes: 'Prefers 8am slots. Responds to email only.',
    customerId: 'C5-L1',
    lastVisit: '28 Jul 2026',
    nextAppointment: 'Today 8:30 am',
    photoUrl: undefined,
  },
  {
    id: 'c6',
    name: 'Isla Trentham',
    initials: 'IT',
    email: 'isla.t@lightpathdesign.co',
    phone: '(415) 555-0562',
    preferredContact: 'SMS',
    preferences: 'Mid-morning',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Standard',
    memberSince: 'Oct 2023',
    visits: 7,
    upcomingCount: 1,
    missedVisits: 0,
    notes: 'New member. Still exploring services.',
    customerId: 'C6-L1',
    lastVisit: '18 Jul 2026',
    nextAppointment: 'Today 10:30 am',
    photoUrl: undefined,
  },
  {
    id: 'c7',
    name: 'Dermot Asante',
    initials: 'DA',
    email: 'd.asante@asantelaw.com',
    phone: '(415) 555-0693',
    preferredContact: 'Call',
    preferences: 'Flexible',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Founding',
    memberSince: 'May 2018',
    visits: 88,
    upcomingCount: 1,
    missedVisits: 1,
    notes: 'Long-standing client. Flexible on timing. Prefers A. Okonjo.',
    customerId: 'C7-L1',
    lastVisit: '04 Aug 2026',
    nextAppointment: 'Today 1:00 pm',
    photoUrl: undefined,
  },
  {
    id: 'c8',
    name: 'Saoirse Whitmore',
    initials: 'SW',
    email: 'saoirse.w@whitmore.ie',
    phone: '(415) 555-0714',
    preferredContact: 'Email',
    preferences: 'Quiet, no music',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Signature',
    memberSince: 'Sep 2020',
    visits: 39,
    upcomingCount: 0,
    missedVisits: 0,
    notes: 'Prefers complete silence during sessions. No background music.',
    customerId: 'C8-L1',
    lastVisit: '25 Jul 2026',
    nextAppointment: undefined,
    photoUrl: undefined,
  },
  {
    id: 'c9',
    name: 'Kofi Mensah',
    initials: 'KM',
    email: 'k.mensah@northlightstudio.co',
    phone: '(415) 555-0827',
    preferredContact: 'SMS',
    preferences: 'Weekday mornings',
    homeLocation: 'Harbor Street',
    balance: 20,
    tier: 'Standard',
    memberSince: 'Apr 2024',
    visits: 4,
    upcomingCount: 1,
    missedVisits: 0,
    notes: 'Recently joined. Booked first extended session for today.',
    customerId: 'C9-L1',
    lastVisit: '28 Jul 2026',
    nextAppointment: 'Today 4:00 pm',
    photoUrl: undefined,
  },
  {
    id: 'c10',
    name: 'Niamh Calloway',
    initials: 'NC',
    email: 'niamhc@duskperfumery.com',
    phone: '(415) 555-0945',
    preferredContact: 'Email',
    preferences: 'Evenings',
    homeLocation: 'Harbor Street',
    balance: 0,
    tier: 'Signature',
    memberSince: 'Nov 2021',
    visits: 19,
    upcomingCount: 1,
    missedVisits: 0,
    notes: 'Prefers evening slots. Regular standard session client.',
    customerId: 'C10-L1',
    lastVisit: '30 Jul 2026',
    nextAppointment: 'Today 5:00 pm',
    photoUrl: undefined,
  },
];

// Today's date for appointments (using a fixed date to match prototype)
const TODAY = '2026-08-06';

// ============ Spa Appointments ============
export const mockSpaAppointments: SpaAppointment[] = [
  // 8:00 am - Cleo, Standard session, A. Okonjo
  {
    id: 'a1',
    customerId: 'c2',
    customerName: 'Cleo Fairbanks',
    customerInitials: 'CF',
    customerTier: 'Signature',
    customerPhone: '(415) 555-0187',
    staffId: 'st1',
    staffName: 'A. Okonjo',
    service: 'Standard session',
    duration: 60,
    room: 'Room 1',
    date: TODAY,
    startTime: '09:00',
    status: 'checked_in',
    checkInTime: '08:58',
  },
  // 8:30 am - Phineas, Consultation, J. Park
  {
    id: 'a2',
    customerId: 'c5',
    customerName: 'Phineas Burke',
    customerInitials: 'PB',
    customerTier: 'Signature',
    customerPhone: '(415) 555-0478',
    staffId: 'st4',
    staffName: 'J. Park',
    service: 'Consultation',
    duration: 30,
    room: 'Suite A',
    date: TODAY,
    startTime: '08:30',
    status: 'completed',
    checkInTime: '08:28',
    checkOutTime: '09:02',
  },
  // 10:30 am - Isla, Standard session, M. Reyes
  {
    id: 'a3',
    customerId: 'c6',
    customerName: 'Isla Trentham',
    customerInitials: 'IT',
    customerTier: 'Standard',
    customerPhone: '(415) 555-0562',
    staffId: 'st2',
    staffName: 'M. Reyes',
    service: 'Standard session',
    duration: 60,
    room: 'Room 3',
    date: TODAY,
    startTime: '10:30',
    status: 'scheduled',
  },
  // 12:00 pm - Adaeze, Standard session, A. Okonjo
  {
    id: 'a4',
    customerId: 'c1',
    customerName: 'Adaeze Nwosu',
    customerInitials: 'AN',
    customerTier: 'Founding',
    customerPhone: '(415) 555-0132',
    staffId: 'st1',
    staffName: 'A. Okonjo',
    service: 'Standard session',
    duration: 60,
    room: 'Room 1',
    date: TODAY,
    startTime: '12:00',
    status: 'scheduled',
  },
  // 1:00 pm - Dermot, Extended session, A. Okonjo
  {
    id: 'a5',
    customerId: 'c7',
    customerName: 'Dermot Asante',
    customerInitials: 'DA',
    customerTier: 'Founding',
    customerPhone: '(415) 555-0693',
    staffId: 'st1',
    staffName: 'A. Okonjo',
    service: 'Extended session',
    duration: 90,
    room: 'Room 2',
    date: TODAY,
    startTime: '13:00',
    status: 'scheduled',
  },
  // 2:00 pm - Marisol, Extended session, M. Reyes
  {
    id: 'a6',
    customerId: 'c4',
    customerName: 'Marisol Venegas',
    customerInitials: 'MV',
    customerTier: 'Founding',
    customerPhone: '(415) 555-0341',
    staffId: 'st2',
    staffName: 'M. Reyes',
    service: 'Extended session',
    duration: 90,
    room: 'Room 3',
    date: TODAY,
    startTime: '14:00',
    status: 'scheduled',
  },
  // 3:30 pm - Adaeze, Consultation, J. Park
  {
    id: 'a7',
    customerId: 'c1',
    customerName: 'Adaeze Nwosu',
    customerInitials: 'AN',
    customerTier: 'Founding',
    customerPhone: '(415) 555-0132',
    staffId: 'st4',
    staffName: 'J. Park',
    service: 'Consultation',
    duration: 30,
    room: 'Suite A',
    date: TODAY,
    startTime: '15:30',
    status: 'scheduled',
  },
  // 4:00 pm - Kofi, Extended session, T. Lindqvist
  {
    id: 'a8',
    customerId: 'c9',
    customerName: 'Kofi Mensah',
    customerInitials: 'KM',
    customerTier: 'Standard',
    customerPhone: '(415) 555-0827',
    staffId: 'st3',
    staffName: 'T. Lindqvist',
    service: 'Extended session',
    duration: 90,
    room: 'Room 4',
    date: TODAY,
    startTime: '16:00',
    status: 'scheduled',
  },
  // 5:00 pm - Niamh, Standard session, T. Lindqvist
  {
    id: 'a9',
    customerId: 'c10',
    customerName: 'Niamh Calloway',
    customerInitials: 'NC',
    customerTier: 'Signature',
    customerPhone: '(415) 555-0945',
    staffId: 'st3',
    staffName: 'T. Lindqvist',
    service: 'Standard session',
    duration: 60,
    room: 'Room 4',
    date: TODAY,
    startTime: '17:00',
    status: 'scheduled',
  },
  // No-show example - Tarquin had a slot that he missed
  {
    id: 'a10',
    customerId: 'c3',
    customerName: 'Tarquin Osei',
    customerInitials: 'TO',
    customerTier: 'Standard',
    customerPhone: '(415) 555-0209',
    staffId: 'st2',
    staffName: 'M. Reyes',
    service: 'Standard session',
    duration: 60,
    room: 'Room 3',
    date: TODAY,
    startTime: '08:00',
    status: 'no_show',
    noShowTime: '08:15',
  },
];

// Visit history per customer (for profile page)
export const mockVisitHistory: Record<string, Array<{
  date: string;
  service: string;
  staff: string;
  location: string;
  outcome: 'Completed' | 'Cancelled' | 'No-show';
}>> = {
  c1: [
    { date: '28 Jul 2026', service: 'Standard session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'Completed' },
    { date: '14 Jul 2026', service: 'Extended session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'Completed' },
    { date: '30 Jun 2026', service: 'Standard session', staff: 'M. Reyes', location: 'Harbor Street', outcome: 'Completed' },
    { date: '16 Jun 2026', service: 'Consultation', staff: 'J. Park', location: 'Harbor Street', outcome: 'Completed' },
    { date: '02 Jun 2026', service: 'Standard session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'Cancelled' },
    { date: '19 May 2026', service: 'Standard session', staff: 'T. Lindqvist', location: 'Harbor Street', outcome: 'Completed' },
  ],
  c2: [
    { date: '21 Jul 2026', service: 'Standard session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'Completed' },
    { date: '07 Jul 2026', service: 'Consultation', staff: 'J. Park', location: 'Harbor Street', outcome: 'Completed' },
    { date: '23 Jun 2026', service: 'Standard session', staff: 'M. Reyes', location: 'Harbor Street', outcome: 'No-show' },
    { date: '09 Jun 2026', service: 'Standard session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'Completed' },
  ],
  c4: [
    { date: '01 Aug 2026', service: 'Extended session', staff: 'M. Reyes', location: 'Harbor Street', outcome: 'Completed' },
    { date: '18 Jul 2026', service: 'Standard session', staff: 'M. Reyes', location: 'Harbor Street', outcome: 'Completed' },
    { date: '04 Jul 2026', service: 'Extended session', staff: 'M. Reyes', location: 'Harbor Street', outcome: 'Completed' },
  ],
  c7: [
    { date: '04 Aug 2026', service: 'Extended session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'Completed' },
    { date: '21 Jul 2026', service: 'Standard session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'Completed' },
    { date: '07 Jul 2026', service: 'Extended session', staff: 'A. Okonjo', location: 'Harbor Street', outcome: 'No-show' },
  ],
};
